### ISSUE TITLE
OOM for large test suites on Node@10.23.0

### ISSUE THREAD

**Issue by bcoe** [googleapis/gapic-generator-typescript#785]
I noticed generating `dialogflow-cx` that we're getting an OOM on Node@10.23.0 if I generate both the `v3` and `v3beta1` suites, and run them at the same time.

In this case, I think we're okay to release just the v3 surface, but it would be good to know where our memory is getting used.

https://github.com/googleapis/nodejs-dialogflow-cx/pull/35

**Comment by alexander-fenster** [comment]
I made a workaround for this for Compute library, and it can be reused for other large test suites.

https://github.com/googleapis/nodejs-compute/blob/diregapic/test/run.ts
https://github.com/googleapis/nodejs-compute/blob/diregapic/package.json#L99

I think this should be enough for the one-off APIs that are too huge.  Also, we are removing Node 10 soon anyway.  I'll close this issue since it has a workaround.
