### ISSUE TITLE
Release Docker image to gcr.io

### ISSUE THREAD

**Issue by orgads** [googleapis/gapic-generator-typescript#911]
Latest version on [gcr.io](https://console.cloud.google.com/gcr/images/gapic-images/GLOBAL/gapic-generator-typescript?gcrImageListsize=30) is 1.1.0 from 09/2020.

Please publish newer releases.

Thanks.

This was requested in the past in #86 but I don't see that it was done.

**Comment by alexander-fenster** [comment]
Hi @orgads, thanks for noticing that - we'll do it this week. We stopped using docker in our production pipeline (we use Bazel for all languages we generate), that's why we never completely automated docker publishing.  But we can surely publish new images for users who prefer running things in docker.

**Comment by orgads** [comment]
Thank you.

If building and running with bazel is easier than docker, consider updating the README.

**Comment by summer-ji-eng** [comment]
Updated the docker
